# Tools

This notebook implements a few useful tools for doing some common analysis tasks.

In [ ]:
#@title Compute target scores (old method)
json_input = "[{\"seed\":3752757,\"deck\":[{\"rank\":8,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":11,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":4,\"suit\":16},{\"rank\":7,\"suit\":16},{\"rank\":11,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":11,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":11,\"suit\":4},{\"rank\":7,\"suit\":4},{\"rank\":7,\"suit\":16},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":4,\"suit\":8},{\"rank\":10,\"suit\":4},{\"rank\":8,\"suit\":8},{\"rank\":4,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":4,\"suit\":1},{\"rank\":3,\"suit\":16},{\"rank\":2,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":3,\"suit\":4},{\"rank\":11,\"suit\":1},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":9,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":9,\"suit\":4},{\"rank\":2,\"suit\":1},{\"rank\":11,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":8,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":3,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":14,\"suit\":16},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":10,\"suit\":4},{\"rank\":13,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":13,\"suit\":16},{\"rank\":5,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":9,\"suit\":16},{\"rank\":9,\"suit\":8},{\"rank\":6,\"suit\":1},{\"rank\":11,\"suit\":8},{\"rank\":14,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":3,\"suit\":4},{\"rank\":14,\"suit\":1},{\"rank\":7,\"suit\":16},{\"rank\":3,\"suit\":4},{\"rank\":10,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":10,\"suit\":1},{\"rank\":9,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":8,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":14,\"suit\":16},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":10,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":6,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":16},{\"rank\":8,\"suit\":16},{\"rank\":9,\"suit\":1},{\"rank\":6,\"suit\":1},{\"rank\":9,\"suit\":16},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":8},{\"rank\":11,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":3,\"suit\":8},{\"rank\":3,\"suit\":16}]}]" #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}


import json
from game import payout_table
from agent import player_agent
from stats import shoe_stats

shoe_data_list = json.loads(json_input)
num_decks = len(shoe_data_list[0]['deck']) // 52

target_payout = payout_table.PayoutTable.default()
advantage = player_agent.advantage_table(num_decks)
agents = [player_agent.SimplePlayerAgent(name='simple'),
          player_agent.HandOnlyAgent(name='hands-only'),
          player_agent.CardCountingAgent(name='card-counting'),
          player_agent.PsychicAgent(name='psychic')]

scores = shoe_stats.analyze_json_list_str(
    json_input, agents=agents, payout=target_payout,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe)

scores_json = shoe_stats.scores_to_json_str(scores)
print(scores_json)

In [ ]:
#@title Compute target scores (new method)

json_input = "[{\"seed\":3752757,\"deck\":[{\"rank\":8,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":11,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":4,\"suit\":16},{\"rank\":7,\"suit\":16},{\"rank\":11,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":11,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":11,\"suit\":4},{\"rank\":7,\"suit\":4},{\"rank\":7,\"suit\":16},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":4,\"suit\":8},{\"rank\":10,\"suit\":4},{\"rank\":8,\"suit\":8},{\"rank\":4,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":4,\"suit\":1},{\"rank\":3,\"suit\":16},{\"rank\":2,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":3,\"suit\":4},{\"rank\":11,\"suit\":1},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":9,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":9,\"suit\":4},{\"rank\":2,\"suit\":1},{\"rank\":11,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":8,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":3,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":14,\"suit\":16},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":10,\"suit\":4},{\"rank\":13,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":13,\"suit\":16},{\"rank\":5,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":9,\"suit\":16},{\"rank\":9,\"suit\":8},{\"rank\":6,\"suit\":1},{\"rank\":11,\"suit\":8},{\"rank\":14,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":3,\"suit\":4},{\"rank\":14,\"suit\":1},{\"rank\":7,\"suit\":16},{\"rank\":3,\"suit\":4},{\"rank\":10,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":10,\"suit\":1},{\"rank\":9,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":8,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":14,\"suit\":16},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":10,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":6,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":16},{\"rank\":8,\"suit\":16},{\"rank\":9,\"suit\":1},{\"rank\":6,\"suit\":1},{\"rank\":9,\"suit\":16},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":8},{\"rank\":11,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":3,\"suit\":8},{\"rank\":3,\"suit\":16}]},{\"seed\":3752758,\"deck\":[{\"rank\":11,\"suit\":16},{\"rank\":7,\"suit\":1},{\"rank\":13,\"suit\":16},{\"rank\":6,\"suit\":4},{\"rank\":9,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":7,\"suit\":16},{\"rank\":2,\"suit\":4},{\"rank\":11,\"suit\":1},{\"rank\":10,\"suit\":8},{\"rank\":3,\"suit\":1},{\"rank\":9,\"suit\":16},{\"rank\":3,\"suit\":8},{\"rank\":10,\"suit\":4},{\"rank\":8,\"suit\":4},{\"rank\":9,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":3,\"suit\":16},{\"rank\":11,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":9,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":12,\"suit\":1},{\"rank\":13,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":2,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":14,\"suit\":1},{\"rank\":12,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":8,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":8,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":9,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":5,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":3,\"suit\":16},{\"rank\":2,\"suit\":1},{\"rank\":10,\"suit\":1},{\"rank\":5,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":8,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":9,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":6,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":8,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":14,\"suit\":8},{\"rank\":11,\"suit\":16},{\"rank\":4,\"suit\":16},{\"rank\":9,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":7,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":12,\"suit\":8},{\"rank\":13,\"suit\":16},{\"rank\":12,\"suit\":4},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":1},{\"rank\":8,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":4},{\"rank\":12,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":13,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":14,\"suit\":8},{\"rank\":6,\"suit\":8},{\"rank\":3,\"suit\":4},{\"rank\":9,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":5,\"suit\":4},{\"rank\":10,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":2,\"suit\":4},{\"rank\":5,\"suit\":4},{\"rank\":10,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":9,\"suit\":1},{\"rank\":4,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":13,\"suit\":8},{\"rank\":5,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":12,\"suit\":1},{\"rank\":13,\"suit\":8},{\"rank\":14,\"suit\":8},{\"rank\":3,\"suit\":4},{\"rank\":3,\"suit\":4},{\"rank\":2,\"suit\":4},{\"rank\":6,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":8,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":4,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":11,\"suit\":4},{\"rank\":6,\"suit\":1},{\"rank\":10,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":10,\"suit\":16},{\"rank\":11,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":4,\"suit\":8},{\"rank\":14,\"suit\":1},{\"rank\":13,\"suit\":4},{\"rank\":10,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":13,\"suit\":1},{\"rank\":7,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":12,\"suit\":8},{\"rank\":2,\"suit\":8},{\"rank\":11,\"suit\":8},{\"rank\":3,\"suit\":16},{\"rank\":5,\"suit\":1},{\"rank\":8,\"suit\":4}]}]" #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}
target_ranks = '2, 4, 6, 9' #@param {type:"string"}


from stats import shoe_stats
from game import payout_table

target_payout = payout_table.PayoutTable.default()
ranks = [int(r) for r in target_ranks.split(',')]

scores = shoe_stats.analyze_json_list_str(
    json_input, agents=None, payout=target_payout,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe,
    ranks=ranks)

scores_json = shoe_stats.scores_to_json_str(scores)
print(scores_json)

In [1]:
from json.decoder import JSONDecodeError
#@title Single shoe
cards = "[{\"seed\":3752757,\"deck\":[{\"rank\":8,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":11,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":4,\"suit\":16},{\"rank\":7,\"suit\":16},{\"rank\":11,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":11,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":11,\"suit\":4},{\"rank\":7,\"suit\":4},{\"rank\":7,\"suit\":16},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":4,\"suit\":8},{\"rank\":10,\"suit\":4},{\"rank\":8,\"suit\":8},{\"rank\":4,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":4,\"suit\":1},{\"rank\":3,\"suit\":16},{\"rank\":2,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":3,\"suit\":4},{\"rank\":11,\"suit\":1},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":9,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":9,\"suit\":4},{\"rank\":2,\"suit\":1},{\"rank\":11,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":8,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":3,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":14,\"suit\":16},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":10,\"suit\":4},{\"rank\":13,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":13,\"suit\":16},{\"rank\":5,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":9,\"suit\":16},{\"rank\":9,\"suit\":8},{\"rank\":6,\"suit\":1},{\"rank\":11,\"suit\":8},{\"rank\":14,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":3,\"suit\":4},{\"rank\":14,\"suit\":1},{\"rank\":7,\"suit\":16},{\"rank\":3,\"suit\":4},{\"rank\":10,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":10,\"suit\":1},{\"rank\":9,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":8,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":14,\"suit\":16},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":10,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":6,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":16},{\"rank\":8,\"suit\":16},{\"rank\":9,\"suit\":1},{\"rank\":6,\"suit\":1},{\"rank\":9,\"suit\":16},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":8},{\"rank\":11,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":3,\"suit\":8},{\"rank\":3,\"suit\":16}]}]" #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}
target_ranks = '2, 6, 11, 16' #@param {type:"string"}
sort = True #@param {type:"boolean"}
SEED = 11111

import collections
import json
import numpy as np
import pandas as pd

from stats import shoe_stats
from game import payout_table
from agent import player_agent
from game import poker_game
from game import card
from game import shoe

seed = np.random.SeedSequence(SEED)

try:
    shoe_data = json.loads(cards)[0]
    draw_shoe = shoe_stats._json_to_shoe(shoe_data)  
    num_decks = draw_shoe.num_decks
except JSONDecodeError:
    card_list = card.card_list(cards)
    num_decks = len(card_list) // 52
    draw_shoe=shoe.Shoe(num_decks=num_decks, card_list=card_list)

game = poker_game.PokerGame(
    num_decks=num_decks, draw_shoe=draw_shoe,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe)
agents = shoe_stats.default_target_agents(num_decks=num_decks, noise_iterations=1, seed=seed)
target_payout = payout_table.PayoutTable.default()

# Play game with each agent
scores_q = collections.deque()
num_hands_q = collections.deque()
history_q = collections.deque()
for agent in agents:
    print(f'playing {agent.name}...')
    game_copy = game.copy()
    player_agent.play_game(game_copy, agent)
    scores_q.append(game_copy.score)
    num_hands_q.append(game_copy.hand_number)
    history_q.append(game_copy.history)

# Show results
agent_names = [agent.name for agent in agents]
results_df = pd.DataFrame(
    data=np.array([scores_q, num_hands_q], dtype=int).T,
    index=agent_names, columns=['scores', 'hands played']
    )
if sort:
    results_df = results_df.sort_values(by='scores')
display(results_df)

if target_ranks:
    ranks = [int(rank) for rank in target_ranks.split(',')]
    targets = shoe_stats.compute_targets(np.array([scores_q]), ranks)[0]
    print(f'targets: {targets}')

playing simple...
playing hands-only...
playing card-counting...
playing advantage...
playing risk-averse...
playing risk-seeking...
playing hands-only-noise-1...
playing card-counting-noise-1...
playing risk-averse-noise-1...
playing risk-seeking-noise-1...
playing advantage-noise-1...
playing psychic...

                       scores  hands played
risk-seeking-noise-1       70            20
risk-seeking               80            20
simple                    210            19
risk-averse-noise-1       235            19
risk-averse               240            20
advantage                 315            23
advantage-noise-1         330            22
hands-only-noise-1        355            21
hands-only                365            21
card-counting-noise-1     365            21
card-counting             375            21
psychic                   735            21

IndexError: index 15 is out of bounds for axis 1 with size 12

In [2]:
from json.decoder import JSONDecodeError
#@title Single shoe
cards = "[{\"seed\":3752757,\"deck\":[{\"rank\":8,\"suit\":1},{\"rank\":13,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":5,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":11,\"suit\":16},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":8},{\"rank\":11,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":4,\"suit\":16},{\"rank\":7,\"suit\":16},{\"rank\":11,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":11,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":6,\"suit\":8},{\"rank\":7,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":11,\"suit\":4},{\"rank\":7,\"suit\":4},{\"rank\":7,\"suit\":16},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":4},{\"rank\":3,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":4,\"suit\":8},{\"rank\":10,\"suit\":4},{\"rank\":8,\"suit\":8},{\"rank\":4,\"suit\":4},{\"rank\":6,\"suit\":16},{\"rank\":4,\"suit\":1},{\"rank\":3,\"suit\":16},{\"rank\":2,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":3,\"suit\":4},{\"rank\":11,\"suit\":1},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":9,\"suit\":1},{\"rank\":8,\"suit\":16},{\"rank\":12,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":8,\"suit\":8},{\"rank\":13,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":6,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":5,\"suit\":16},{\"rank\":9,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":9,\"suit\":4},{\"rank\":2,\"suit\":1},{\"rank\":11,\"suit\":4},{\"rank\":4,\"suit\":8},{\"rank\":8,\"suit\":1},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":8},{\"rank\":6,\"suit\":16},{\"rank\":11,\"suit\":8},{\"rank\":3,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":14,\"suit\":1},{\"rank\":4,\"suit\":16},{\"rank\":14,\"suit\":4},{\"rank\":12,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":14,\"suit\":16},{\"rank\":8,\"suit\":1},{\"rank\":7,\"suit\":4},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":1},{\"rank\":8,\"suit\":4},{\"rank\":5,\"suit\":1},{\"rank\":10,\"suit\":4},{\"rank\":13,\"suit\":1},{\"rank\":12,\"suit\":8},{\"rank\":9,\"suit\":8},{\"rank\":7,\"suit\":8},{\"rank\":2,\"suit\":16},{\"rank\":13,\"suit\":16},{\"rank\":5,\"suit\":8},{\"rank\":10,\"suit\":8},{\"rank\":9,\"suit\":16},{\"rank\":9,\"suit\":8},{\"rank\":6,\"suit\":1},{\"rank\":11,\"suit\":8},{\"rank\":14,\"suit\":8},{\"rank\":10,\"suit\":1},{\"rank\":3,\"suit\":4},{\"rank\":14,\"suit\":1},{\"rank\":7,\"suit\":16},{\"rank\":3,\"suit\":4},{\"rank\":10,\"suit\":4},{\"rank\":14,\"suit\":16},{\"rank\":10,\"suit\":1},{\"rank\":9,\"suit\":1},{\"rank\":3,\"suit\":1},{\"rank\":12,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":16},{\"rank\":13,\"suit\":8},{\"rank\":8,\"suit\":4},{\"rank\":13,\"suit\":4},{\"rank\":4,\"suit\":1},{\"rank\":10,\"suit\":16},{\"rank\":5,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":16},{\"rank\":14,\"suit\":16},{\"rank\":4,\"suit\":4},{\"rank\":14,\"suit\":4},{\"rank\":10,\"suit\":8},{\"rank\":2,\"suit\":1},{\"rank\":6,\"suit\":4},{\"rank\":2,\"suit\":8},{\"rank\":2,\"suit\":4},{\"rank\":3,\"suit\":16},{\"rank\":8,\"suit\":16},{\"rank\":9,\"suit\":1},{\"rank\":6,\"suit\":1},{\"rank\":9,\"suit\":16},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":1},{\"rank\":7,\"suit\":1},{\"rank\":5,\"suit\":8},{\"rank\":11,\"suit\":16},{\"rank\":7,\"suit\":8},{\"rank\":11,\"suit\":4},{\"rank\":13,\"suit\":16},{\"rank\":2,\"suit\":8},{\"rank\":12,\"suit\":1},{\"rank\":3,\"suit\":8},{\"rank\":3,\"suit\":16}]}]" #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}
target_ranks = '2, 6, 11, 16' #@param {type:"string"}
sort = True #@param {type:"boolean"}
SEED = 12345

import collections
import json
import numpy as np
import pandas as pd

from stats import shoe_stats
from game import payout_table
from agent import player_agent
from game import poker_game
from game import card
from game import shoe

seed = np.random.SeedSequence(SEED)

try:
    shoe_data = json.loads(cards)[0]
    draw_shoe = shoe_stats._json_to_shoe(shoe_data)  
    num_decks = draw_shoe.num_decks
except JSONDecodeError:
    card_list = card.card_list(cards)
    num_decks = len(card_list) // 52
    draw_shoe=shoe.Shoe(num_decks=num_decks, card_list=card_list)

game = poker_game.PokerGame(
    num_decks=num_decks, draw_shoe=draw_shoe,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe)
agents = shoe_stats.default_target_agents(num_decks=num_decks, seed=seed)
target_payout = payout_table.PayoutTable.default()

# Play game with each agent
scores_q = collections.deque()
num_hands_q = collections.deque()
history_q = collections.deque()
for agent in agents:
    print(f'playing {agent.name}...')
    game_copy = game.copy()
    player_agent.play_game(game_copy, agent)
    scores_q.append(game_copy.score)
    num_hands_q.append(game_copy.hand_number)
    history_q.append(game_copy.history)

# Show results
agent_names = [agent.name for agent in agents]
results_df = pd.DataFrame(
    data=np.array([scores_q, num_hands_q], dtype=int).T,
    index=agent_names, columns=['scores', 'hands played']
    )
if sort:
    results_df = results_df.sort_values(by='scores')
display(results_df)

if target_ranks:
    ranks = [int(rank) for rank in target_ranks.split(',')]
    targets = shoe_stats.compute_targets(np.array([scores_q]), ranks)[0]
    print(f'targets: {targets}')

playing simple...
playing hands-only...
playing card-counting...
playing advantage...
playing risk-averse...
playing risk-seeking...
playing hands-only-noise...
playing card-counting-noise...
playing risk-averse-noise...
playing risk-seeking-noise...
playing advantage-noise...
playing hands-only-noise-2...
playing card-counting-noise-2...
playing risk-averse-noise-2...
playing risk-seeking-noise-2...
playing advantage-noise-2...
playing psychic...

                       scores  hands played
risk-seeking-noise-2       70            20
risk-seeking               80            20
risk-seeking-noise        130            19
card-counting-noise-2     190            21
simple                    210            19
risk-averse               240            20
risk-averse-noise-2       295            19
hands-only-noise-2        310            21
advantage                 315            23
advantage-noise           315            22
risk-averse-noise         325            21
hands-only-noise          350            21
card-counting-noise       365            22
hands-only                365            21
card-counting             375            21
advantage-noise-2         380            24
psychic                   735            21

targets: [ 80 240 325 380]

In [3]:
seed = np.random.SeedSequence()
seed

SeedSequence(
    entropy=39574818912477260871823124002387806558,
)

# Probabilities

In [19]:
from game import card
from game import poker_game
from game import shoe
from stats import shoe_stats

card_list = ('KD JH 4S 5H JD 8S QS 9D 5D 2C 5S 6C 3D 9D 9D 7C 7H 8D 6H 6H 3S 10S '
             'JS QD AH JH JD 2S 10H 6C 5H 6S 6H 7S 8S KS 3D 9C 7D 10C 3C 2H 5S 7S '
             '3D QC AC QH 4C 2D 5S 8H 9S 2C 5D AS 3H QC 2H 5H 2H QD AC 10S AH QD '
             'JC 6D 9H 5D 3S AS 4D JC 10D 2S KD 8D 10D JD 7C 7H AD 3S QH 5C 8C 3C '
             'KD KC KC 2D 4D 10D AD QS AC 9C 8D 8H 4D 4S 4H KS 5C 3C 6D KC 9C 10H '
             '2D 4C KH 7D 10S 6S 4S QS JS JH 2S 10C 9H 6D AS 7D 6C 9S 5C 8C 10C 4H '
             'AD 6S KH 8C 3H 7C 8H QC AH 8S 10H 9S JC 3H 4H KH 2C JS 4C 7S KS QH 9H 7H')
game = poker_game.PokerGame(num_decks=3,
                            draw_shoe=shoe.Shoe(card_list, num_decks=3),
                            allow_short_shoe=True)
agents = shoe_stats.default_target_agents(num_decks=3)
game_info_list = shoe_stats.play_games(games=[game], agents=agents)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.48s/it]

In [59]:
anames = [a.name for a in agents]
for name, traj in zip(anames, out[0][2]):
    payouts = np.array([gi.payout for gi in traj])
    print(f'{name}: {np.sort(payouts)[::-1]}')

simple: [70 20 15 15 15 10 10 10 10 10  0  0  0  0  0  0  0  0]
hands-only: [70 70 15 15 10 10 10 10 10 10  0  0  0  0  0  0  0  0  0  0]
card-counting: [70 60 20 15 10 10 10 10 10 10  0  0  0  0  0  0  0  0  0  0]
advantage: [60 20 20 15 10 10 10 10 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
risk-averse: [50 20 15 15 10 10 10 10  0  0  0  0  0  0  0  0  0  0  0  0]
risk-seeking: [20 15 10 10 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
risk-averse-noise: [20 20 15 15 15 10 10 10 10 10  0  0  0  0  0  0  0  0  0  0]
risk-seeking-noise: [20 20 15 10 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
advantage-noise: [70 20 20 20 15 10 10 10 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
psychic: [70 70 60 60 60 60 50 50 50 20 15 15 15 15 10 10 10 10  0  0  0  0  0]

In [20]:
game_info_list[0][2][1]

[GameMove(initial_hand=Hand([4♠, 5♡, J♢, J♡, K♢]), held=Hand([J♢, J♡]), final_hand=Hand([8♠, 9♢, J♢, J♡, Q♠]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([2♣, 3♢, 5♢, 5♠, 6♣]), held=Hand([5♢, 5♠]), final_hand=Hand([5♢, 5♠, 7♣, 9♢, 9♢]), payout=15, info=({},)),
 GameMove(initial_hand=Hand([3♠, 6♡, 6♡, 7♡, 8♢]), held=Hand([6♡, 6♡, 7♡]), final_hand=Hand([6♡, 6♡, 7♡, 10♠, J♠]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([A♡, 2♠, J♢, J♡, Q♢]), held=Hand([J♢, J♡]), final_hand=Hand([5♡, 6♣, 10♡, J♢, J♡]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([6♡, 6♠, 7♠, 8♠, K♠]), held=Hand([6♠, 7♠, 8♠, K♠]), final_hand=Hand([3♢, 6♠, 7♠, 8♠, K♠]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([2♡, 3♣, 7♢, 9♣, 10♣]), held=Hand([3♣, 9♣, 10♣]), final_hand=Hand([3♣, 5♠, 7♠, 9♣, 10♣]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([A♣, 3♢, 4♣, Q♣, Q♡]), held=Hand([Q♣, Q♡]), final_hand=Hand([2♢, 5♠, 8♡, Q♣, Q♡]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([A♠, 2♣, 3♡, 5♢, 9♠]), held=Hand([A♠]), final_hand=Hand([A♠, 2♡, 2♡, 5♡, Q♣]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([A♣, A♡, 10♠, Q♢, Q♢]), held=Hand([A♣, A♡, Q♢, Q♢]), final_hand=Hand([A♣, A♡, J♣, Q♢, Q♢]), payout=15, info=({},)),
 GameMove(initial_hand=Hand([A♠, 3♠, 5♢, 6♢, 9♡]), held=Hand([A♠]), final_hand=Hand([A♠, 2♠, 4♢, 10♢, J♣]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([7♣, 8♢, 10♢, J♢, K♢]), held=Hand([10♢, J♢, K♢]), final_hand=Hand([A♢, 7♡, 10♢, J♢, K♢]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([3♣, 3♠, 5♣, 8♣, Q♡]), held=Hand([3♣, 3♠]), final_hand=Hand([3♣, 3♠, K♣, K♣, K♢]), payout=70, info=({},)),
 GameMove(initial_hand=Hand([A♢, 2♢, 4♢, 10♢, Q♠]), held=Hand([A♢, 2♢, 4♢, 10♢]), final_hand=Hand([A♣, A♢, 2♢, 4♢, 10♢]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([4♢, 4♠, 8♢, 8♡, 9♣]), held=Hand([4♢, 4♠, 8♢, 8♡]), final_hand=Hand([4♢, 4♡, 4♠, 8♢, 8♡]), payout=70, info=({},)),
 GameMove(initial_hand=Hand([3♣, 5♣, 6♢, K♣, K♠]), held=Hand([K♣, K♠]), final_hand=Hand([2♢, 9♣, 10♡, K♣, K♠]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([4♣, 6♠, 7♢, 10♠, K♡]), held=Hand([K♡]), final_hand=Hand([4♠, J♡, J♠, Q♠, K♡]), payout=10, info=({},)),
 GameMove(initial_hand=Hand([A♠, 2♠, 6♢, 9♡, 10♣]), held=Hand([A♠]), final_hand=Hand([A♠, 5♣, 6♣, 7♢, 9♠]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([A♢, 4♡, 6♠, 8♣, 10♣]), held=Hand([A♢]), final_hand=Hand([A♢, 3♡, 7♣, 8♣, K♡]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([A♡, 8♡, 8♠, 10♡, Q♣]), held=Hand([8♡, 8♠]), final_hand=Hand([3♡, 8♡, 8♠, 9♠, J♣]), payout=0, info=({},)),
 GameMove(initial_hand=Hand([2♣, 4♣, 4♡, J♠, K♡]), held=Hand([4♣, 4♡]), final_hand=Hand([4♣, 4♡, 7♠, Q♡, K♠]), payout=0, info=({},))]

In [45]:
import pandas as pd

scores, _, _ = list(zip(*out))
scores
scores_df = pd.DataFrame(scores[0], index=[a.name for a in agents], columns=['score'])
display(scores_df.sort_values(by='score'))
display(scores_df)
shoe_stats.compute_targets(scores)

                    score
risk-seeking           65
risk-seeking-noise     75
risk-averse-noise     135
risk-averse           140
advantage             165
simple                185
advantage-noise       185
card-counting         225
hands-only            230
psychic               650

                    score
simple                185
hands-only            230
card-counting         225
advantage             165
risk-averse           140
risk-seeking           65
risk-averse-noise     135
risk-seeking-noise     75
advantage-noise       185
psychic               650

array([[ 75, 140, 185, 225]])

## Compute Target Scores

This tool computes target scores that roughly correspond to *ok*, *good*, *better* and *great* for a given card shoe.

This tool plays specified card shoes using ten different agents of various skill levels and play styles and reports their final score. Some agents play better than others, but the inherent randomness of the game will still lead to the less-good agents beating out their betters sometimes. The only exception is the *psychic* agent, which explicitly cheats always reports the absolute highest possible hand on any given shoe.


### Input format

Shoes are specified in the JSON format produced by the Over/Under implementation (Build 0.6.17 and later), and have the following format:

    [{seed: <int>, deck:[{rank: <int>, suit: <int>}, ...]},
     {seed: <int>, deck:[{rank: <int>, suit: <int>}, ...]},
     ...]

Ace is represented as rank 14, and *suit* will be one of (1, 4, 8, 16), which corresponds to spades, clubs, hearts and diamonds respectively.

## Output format

Output will be a JSON string formatted as:

    [{"<seed1>", [<target1>, <target2>, <target3>, <target4>]},
     {"<seed2>", [<target1>, <target2>, <target3>, <target4>]},
      ...]

where targets are presented in agent order (i.e. "good" to "best"). Note that the output does not include the number of decks in the shoe, so be sure to associate the output with the correct input.

In [12]:
#@title 4-agent targets
json_input = '[{"seed":752705,"deck":[{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4}]},{"seed":752706,"deck":[{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1}]},{"seed":752707,"deck":[{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1}]},{"seed":752708,"deck":[{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":16}]},{"seed":752709,"deck":[{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":1}]},{"seed":752710,"deck":[{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":8}]},{"seed":752711,"deck":[{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":16}]},{"seed":752712,"deck":[{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":4}]},{"seed":752713,"deck":[{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16}]},{"seed":752714,"deck":[{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":8}]},{"seed":752715,"deck":[{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":4}]},{"seed":752716,"deck":[{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":8}]},{"seed":752717,"deck":[{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":4}]},{"seed":752718,"deck":[{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":4}]},{"seed":752719,"deck":[{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":16}]},{"seed":752720,"deck":[{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8}]},{"seed":752721,"deck":[{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":4}]},{"seed":752722,"deck":[{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16}]},{"seed":752723,"deck":[{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":16}]},{"seed":752724,"deck":[{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":8}]},{"seed":752725,"deck":[{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16}]},{"seed":752726,"deck":[{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8}]},{"seed":752727,"deck":[{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":16}]},{"seed":752728,"deck":[{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16}]},{"seed":752729,"deck":[{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":16}]},{"seed":752730,"deck":[{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16}]},{"seed":752731,"deck":[{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1}]},{"seed":752732,"deck":[{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":16}]},{"seed":752733,"deck":[{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4}]},{"seed":752734,"deck":[{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4}]},{"seed":752735,"deck":[{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8}]},{"seed":752736,"deck":[{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":1}]},{"seed":752737,"deck":[{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16}]},{"seed":752738,"deck":[{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":1}]},{"seed":752739,"deck":[{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4}]},{"seed":752740,"deck":[{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16}]},{"seed":752741,"deck":[{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":1}]},{"seed":752742,"deck":[{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16}]},{"seed":752743,"deck":[{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":16}]},{"seed":752744,"deck":[{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":4}]},{"seed":752745,"deck":[{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1}]},{"seed":752746,"deck":[{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":1}]},{"seed":752747,"deck":[{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":8}]},{"seed":752748,"deck":[{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":4}]},{"seed":752749,"deck":[{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4}]},{"seed":752750,"deck":[{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1}]},{"seed":752751,"deck":[{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8}]},{"seed":752752,"deck":[{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4}]},{"seed":752753,"deck":[{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16}]},{"seed":752754,"deck":[{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8}]},{"seed":752755,"deck":[{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":1}]},{"seed":752756,"deck":[{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":1}]},{"seed":752757,"deck":[{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8}]},{"seed":752758,"deck":[{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":8}]},{"seed":752759,"deck":[{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":8}]},{"seed":752760,"deck":[{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1}]},{"seed":752761,"deck":[{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16}]},{"seed":752762,"deck":[{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":8}]},{"seed":752763,"deck":[{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":1}]},{"seed":752764,"deck":[{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4}]},{"seed":752765,"deck":[{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4}]},{"seed":752766,"deck":[{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":16}]},{"seed":752767,"deck":[{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16}]},{"seed":752768,"deck":[{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16}]},{"seed":752769,"deck":[{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16}]},{"seed":752770,"deck":[{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8}]},{"seed":752771,"deck":[{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1}]},{"seed":752772,"deck":[{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4}]},{"seed":752773,"deck":[{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1}]},{"seed":752774,"deck":[{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4}]},{"seed":752775,"deck":[{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":4}]},{"seed":752776,"deck":[{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16}]},{"seed":752777,"deck":[{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16}]},{"seed":752778,"deck":[{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4}]},{"seed":752779,"deck":[{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1}]},{"seed":752780,"deck":[{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8}]},{"seed":752781,"deck":[{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":4}]},{"seed":752782,"deck":[{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8}]},{"seed":752783,"deck":[{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1}]},{"seed":752784,"deck":[{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16}]},{"seed":752785,"deck":[{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16}]},{"seed":752786,"deck":[{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1}]},{"seed":752787,"deck":[{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16}]},{"seed":752788,"deck":[{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":16}]},{"seed":752789,"deck":[{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":8}]},{"seed":752790,"deck":[{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":16}]},{"seed":752791,"deck":[{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":1}]},{"seed":752792,"deck":[{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4}]},{"seed":752793,"deck":[{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1}]},{"seed":752794,"deck":[{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16}]},{"seed":752795,"deck":[{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1}]},{"seed":752796,"deck":[{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":8}]},{"seed":752797,"deck":[{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1}]},{"seed":752798,"deck":[{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8}]},{"seed":752799,"deck":[{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4}]},{"seed":752800,"deck":[{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4}]},{"seed":752801,"deck":[{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16}]},{"seed":752802,"deck":[{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4}]},{"seed":752803,"deck":[{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16}]},{"seed":752804,"deck":[{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1}]}]' #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}


import json
from game import payout_table
from agent import player_agent
from stats import shoe_stats

shoe_data_list = json.loads(json_input)
num_decks = len(shoe_data_list[0]['deck']) // 52

target_payout = payout_table.PayoutTable.default()
advantage = player_agent.advantage_table(num_decks)
agents = [player_agent.SimplePlayerAgent(name='simple'),
          player_agent.HandOnlyAgent(name='hands-only'),
          player_agent.CardCountingAgent(name='card-counting'),
          player_agent.PsychicAgent(name='psychic')]

scores = shoe_stats.analyze_json_list_str(
    json_input, agents=agents, payout=target_payout,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe)

scores_json = shoe_stats.scores_to_json_str(scores)
print(scores_json)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:46<00:00,  2.15it/s]

[{"752705": [265, 155, 355, 720]}, {"752706": [170, 170, 275, 670]}, {"752707": [175, 270, 325, 985]}, {"752708": [180, 320, 190, 880]}, {"752709": [255, 210, 220, 880]}, {"752710": [180, 300, 280, 970]}, {"752711": [220, 290, 310, 945]}, {"752712": [320, 135, 295, 890]}, {"752713": [195, 255, 260, 925]}, {"752714": [320, 320, 260, 1025]}, {"752715": [220, 310, 340, 790]}, {"752716": [230, 440, 375, 970]}, {"752717": [335, 270, 295, 1800]}, {"752718": [185, 285, 370, 985]}, {"752719": [310, 405, 415, 865]}, {"752720": [145, 230, 300, 965]}, {"752721": [175, 350, 290, 900]}, {"752722": [240, 260, 310, 920]}, {"752723": [200, 345, 310, 825]}, {"752724": [120, 415, 355, 725]}, {"752725": [310, 225, 270, 835]}, {"752726": [205, 315, 370, 820]}, {"752727": [340, 335, 290, 960]}, {"752728": [340, 335, 335, 825]}, {"752729": [185, 225, 320, 845]}, {"752730": [360, 135, 370, 1010]}, {"752731": [150, 260, 285, 755]}, {"752732": [215, 245, 175, 820]}, {"752733": [235, 280, 255, 835]}, {"752734": [245, 185, 185, 785]}, {"752735": [180, 345, 375, 700]}, {"752736": [140, 280, 215, 905]}, {"752737": [320, 240, 365, 1925]}, {"752738": [230, 290, 305, 795]}, {"752739": [145, 300, 260, 805]}, {"752740": [230, 540, 475, 1045]}, {"752741": [175, 285, 275, 790]}, {"752742": [90, 180, 285, 820]}, {"752743": [220, 190, 255, 845]}, {"752744": [170, 290, 295, 860]}, {"752745": [220, 275, 215, 930]}, {"752746": [195, 325, 285, 900]}, {"752747": [135, 170, 175, 675]}, {"752748": [370, 650, 550, 1185]}, {"752749": [245, 285, 390, 935]}, {"752750": [165, 355, 335, 965]}, {"752751": [300, 310, 345, 950]}, {"752752": [170, 245, 280, 775]}, {"752753": [220, 285, 345, 820]}, {"752754": [325, 365, 475, 995]}, {"752755": [155, 195, 280, 720]}, {"752756": [165, 230, 235, 955]}, {"752757": [325, 175, 375, 1030]}, {"752758": [175, 210, 245, 815]}, {"752759": [245, 375, 375, 860]}, {"752760": [255, 285, 345, 885]}, {"752761": [170, 255, 295, 680]}, {"752762": [250, 350, 300, 960]}, {"752763": [225, 220, 240, 705]}, {"752764": [300, 345, 380, 1030]}, {"752765": [250, 370, 335, 1000]}, {"752766": [210, 365, 195, 805]}, {"752767": [350, 390, 265, 890]}, {"752768": [180, 185, 185, 835]}, {"752769": [245, 270, 355, 1065]}, {"752770": [285, 350, 385, 810]}, {"752771": [250, 385, 275, 1020]}, {"752772": [170, 295, 310, 760]}, {"752773": [130, 400, 300, 840]}, {"752774": [225, 290, 270, 790]}, {"752775": [345, 410, 345, 1040]}, {"752776": [185, 210, 270, 745]}, {"752777": [235, 280, 455, 940]}, {"752778": [240, 230, 295, 840]}, {"752779": [190, 370, 270, 940]}, {"752780": [140, 165, 220, 770]}, {"752781": [405, 530, 545, 955]}, {"752782": [215, 360, 380, 905]}, {"752783": [150, 240, 230, 675]}, {"752784": [130, 460, 425, 955]}, {"752785": [200, 220, 245, 845]}, {"752786": [240, 255, 195, 815]}, {"752787": [310, 210, 210, 885]}, {"752788": [335, 370, 400, 990]}, {"752789": [245, 295, 355, 1115]}, {"752790": [170, 185, 190, 900]}, {"752791": [110, 305, 370, 865]}, {"752792": [215, 240, 230, 935]}, {"752793": [360, 455, 420, 1880]}, {"752794": [155, 270, 300, 1920]}, {"752795": [400, 315, 590, 1080]}, {"752796": [200, 230, 255, 840]}, {"752797": [165, 270, 195, 775]}, {"752798": [295, 290, 285, 860]}, {"752799": [360, 625, 600, 2085]}, {"752800": [480, 345, 520, 995]}, {"752801": [180, 290, 160, 875]}, {"752802": [150, 290, 300, 955]}, {"752803": [110, 205, 255, 770]}, {"752804": [320, 235, 245, 955]}]

In [11]:
len(shoe_data_list[0]['deck']) // 52

4

In [1]:
#@title Extended targets

json_input = '[{"seed":752705,"deck":[{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4}]},{"seed":752706,"deck":[{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1}]},{"seed":752707,"deck":[{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1}]},{"seed":752708,"deck":[{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":16}]},{"seed":752709,"deck":[{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":1}]},{"seed":752710,"deck":[{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":8}]},{"seed":752711,"deck":[{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":16}]},{"seed":752712,"deck":[{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":4}]},{"seed":752713,"deck":[{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16}]},{"seed":752714,"deck":[{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":8}]},{"seed":752715,"deck":[{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":4}]},{"seed":752716,"deck":[{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":8}]},{"seed":752717,"deck":[{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":4}]},{"seed":752718,"deck":[{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":4}]},{"seed":752719,"deck":[{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":16}]},{"seed":752720,"deck":[{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8}]},{"seed":752721,"deck":[{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":4}]},{"seed":752722,"deck":[{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16}]},{"seed":752723,"deck":[{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":16}]},{"seed":752724,"deck":[{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":8}]},{"seed":752725,"deck":[{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16}]},{"seed":752726,"deck":[{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8}]},{"seed":752727,"deck":[{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":16}]},{"seed":752728,"deck":[{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16}]},{"seed":752729,"deck":[{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":16}]},{"seed":752730,"deck":[{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16}]},{"seed":752731,"deck":[{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1}]},{"seed":752732,"deck":[{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":16}]},{"seed":752733,"deck":[{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4}]},{"seed":752734,"deck":[{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4}]},{"seed":752735,"deck":[{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8}]},{"seed":752736,"deck":[{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":1}]},{"seed":752737,"deck":[{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16}]},{"seed":752738,"deck":[{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":1}]},{"seed":752739,"deck":[{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4}]},{"seed":752740,"deck":[{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16}]},{"seed":752741,"deck":[{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":1}]},{"seed":752742,"deck":[{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16}]},{"seed":752743,"deck":[{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":16}]},{"seed":752744,"deck":[{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":4}]},{"seed":752745,"deck":[{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1}]},{"seed":752746,"deck":[{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":1}]},{"seed":752747,"deck":[{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":8}]},{"seed":752748,"deck":[{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":4}]},{"seed":752749,"deck":[{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4}]},{"seed":752750,"deck":[{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1}]},{"seed":752751,"deck":[{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8}]},{"seed":752752,"deck":[{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4}]},{"seed":752753,"deck":[{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16}]},{"seed":752754,"deck":[{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":8}]},{"seed":752755,"deck":[{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":1}]},{"seed":752756,"deck":[{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":1}]},{"seed":752757,"deck":[{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8}]},{"seed":752758,"deck":[{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":4,"suit":8}]},{"seed":752759,"deck":[{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":8}]},{"seed":752760,"deck":[{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":1}]},{"seed":752761,"deck":[{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":16}]},{"seed":752762,"deck":[{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":8}]},{"seed":752763,"deck":[{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":13,"suit":1}]},{"seed":752764,"deck":[{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":4}]},{"seed":752765,"deck":[{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4}]},{"seed":752766,"deck":[{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":16}]},{"seed":752767,"deck":[{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16}]},{"seed":752768,"deck":[{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16}]},{"seed":752769,"deck":[{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16}]},{"seed":752770,"deck":[{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8}]},{"seed":752771,"deck":[{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":1}]},{"seed":752772,"deck":[{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4}]},{"seed":752773,"deck":[{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":8,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1}]},{"seed":752774,"deck":[{"rank":11,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4}]},{"seed":752775,"deck":[{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":4}]},{"seed":752776,"deck":[{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16}]},{"seed":752777,"deck":[{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16}]},{"seed":752778,"deck":[{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":4}]},{"seed":752779,"deck":[{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":4,"suit":4},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":1}]},{"seed":752780,"deck":[{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":4,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":8}]},{"seed":752781,"deck":[{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":9,"suit":16},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":16},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":4}]},{"seed":752782,"deck":[{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8}]},{"seed":752783,"deck":[{"rank":14,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1}]},{"seed":752784,"deck":[{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":2,"suit":16}]},{"seed":752785,"deck":[{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":14,"suit":16},{"rank":8,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16}]},{"seed":752786,"deck":[{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":1}]},{"seed":752787,"deck":[{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":8},{"rank":4,"suit":8},{"rank":12,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":16},{"rank":14,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":16},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":10,"suit":16}]},{"seed":752788,"deck":[{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":16},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":16},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":16}]},{"seed":752789,"deck":[{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":5,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":16},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":8},{"rank":4,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":1},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":16},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":8}]},{"seed":752790,"deck":[{"rank":7,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":8,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":12,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":7,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":16}]},{"seed":752791,"deck":[{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":6,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":4},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":8},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":14,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":2,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":14,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":4,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":8},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":4},{"rank":14,"suit":8},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":3,"suit":4},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":1}]},{"seed":752792,"deck":[{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":9,"suit":16},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":5,"suit":8},{"rank":2,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":12,"suit":8},{"rank":9,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":16},{"rank":10,"suit":8},{"rank":10,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":14,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":1},{"rank":14,"suit":16},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":2,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":8},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4}]},{"seed":752793,"deck":[{"rank":8,"suit":4},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":8},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":13,"suit":8},{"rank":9,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":13,"suit":1},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":4},{"rank":14,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":4},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":4},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":16},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":8},{"rank":12,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":8},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":8},{"rank":8,"suit":1}]},{"seed":752794,"deck":[{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":11,"suit":4},{"rank":10,"suit":8},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":11,"suit":8},{"rank":13,"suit":8},{"rank":10,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":13,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":6,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":13,"suit":16},{"rank":5,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":12,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":14,"suit":8},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":3,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":8},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":13,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":16},{"rank":2,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":2,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":12,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16}]},{"seed":752795,"deck":[{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":8},{"rank":3,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":5,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":16},{"rank":9,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":16},{"rank":11,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":4},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":16},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":16},{"rank":8,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":14,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":13,"suit":4},{"rank":8,"suit":8},{"rank":8,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":9,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":11,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":8},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":16},{"rank":3,"suit":16},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":4},{"rank":14,"suit":8},{"rank":8,"suit":1},{"rank":8,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":6,"suit":1},{"rank":7,"suit":4},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":7,"suit":1},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":6,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":16},{"rank":12,"suit":16},{"rank":13,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":1},{"rank":12,"suit":1},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":3,"suit":8},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":8},{"rank":5,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":1}]},{"seed":752796,"deck":[{"rank":9,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":8},{"rank":9,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":14,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":4,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":16},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":1},{"rank":6,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":4},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":3,"suit":1},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":14,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":10,"suit":8},{"rank":14,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":8},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":4},{"rank":3,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":5,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":13,"suit":4},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":10,"suit":16},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":10,"suit":8}]},{"seed":752797,"deck":[{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":8,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":10,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":4},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":1},{"rank":3,"suit":8},{"rank":5,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":8},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":5,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":6,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":11,"suit":16},{"rank":2,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":8},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":4},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":16},{"rank":8,"suit":16},{"rank":14,"suit":8},{"rank":14,"suit":1},{"rank":5,"suit":8},{"rank":3,"suit":8},{"rank":2,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":6,"suit":16},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":2,"suit":1},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":12,"suit":16},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":9,"suit":1},{"rank":4,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":10,"suit":1},{"rank":4,"suit":4},{"rank":7,"suit":8},{"rank":9,"suit":16},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":1},{"rank":4,"suit":4},{"rank":9,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":11,"suit":8},{"rank":10,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":4},{"rank":6,"suit":1}]},{"seed":752798,"deck":[{"rank":6,"suit":8},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":16},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":11,"suit":16},{"rank":11,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":1},{"rank":8,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":4},{"rank":7,"suit":1},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":14,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":6,"suit":16},{"rank":12,"suit":8},{"rank":9,"suit":16},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":3,"suit":4},{"rank":10,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":13,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":7,"suit":16},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":12,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":2,"suit":8},{"rank":14,"suit":8},{"rank":8,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":11,"suit":16},{"rank":5,"suit":16},{"rank":13,"suit":8},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":3,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":13,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":1},{"rank":13,"suit":1},{"rank":4,"suit":16},{"rank":5,"suit":8},{"rank":14,"suit":16},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":7,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":8},{"rank":7,"suit":16},{"rank":11,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":11,"suit":16},{"rank":9,"suit":1},{"rank":10,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":8}]},{"seed":752799,"deck":[{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":12,"suit":8},{"rank":3,"suit":8},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":8},{"rank":11,"suit":1},{"rank":13,"suit":8},{"rank":5,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":11,"suit":16},{"rank":9,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":2,"suit":1},{"rank":9,"suit":4},{"rank":13,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":1},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":4,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":16},{"rank":3,"suit":16},{"rank":5,"suit":16},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":9,"suit":8},{"rank":5,"suit":8},{"rank":11,"suit":8},{"rank":7,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":16},{"rank":14,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":16},{"rank":9,"suit":16},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":13,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":4},{"rank":2,"suit":16},{"rank":11,"suit":4},{"rank":5,"suit":4},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":3,"suit":16},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":4,"suit":8},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":10,"suit":4},{"rank":13,"suit":1},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":11,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":3,"suit":8},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":4,"suit":8},{"rank":4,"suit":16},{"rank":8,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":11,"suit":16},{"rank":6,"suit":16},{"rank":2,"suit":16},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":6,"suit":1},{"rank":12,"suit":4},{"rank":12,"suit":16},{"rank":11,"suit":4},{"rank":13,"suit":1},{"rank":7,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":16},{"rank":2,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":1},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":4,"suit":8},{"rank":2,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":8},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":13,"suit":8},{"rank":7,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":16},{"rank":10,"suit":4},{"rank":12,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":9,"suit":1},{"rank":9,"suit":8},{"rank":13,"suit":4},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":10,"suit":4},{"rank":4,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":8},{"rank":2,"suit":8},{"rank":14,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":12,"suit":4},{"rank":14,"suit":4},{"rank":9,"suit":4}]},{"seed":752800,"deck":[{"rank":2,"suit":1},{"rank":10,"suit":4},{"rank":13,"suit":16},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":8},{"rank":9,"suit":16},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":4},{"rank":12,"suit":1},{"rank":9,"suit":16},{"rank":2,"suit":4},{"rank":5,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":4},{"rank":10,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":16},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":14,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":13,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":14,"suit":16},{"rank":13,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":16},{"rank":7,"suit":4},{"rank":4,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":8},{"rank":14,"suit":4},{"rank":2,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":8,"suit":16},{"rank":5,"suit":16},{"rank":4,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":4},{"rank":10,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":4},{"rank":9,"suit":1},{"rank":5,"suit":4},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":7,"suit":1},{"rank":10,"suit":4},{"rank":2,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":8},{"rank":12,"suit":4},{"rank":5,"suit":8},{"rank":3,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":16},{"rank":10,"suit":16},{"rank":6,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":9,"suit":4},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":6,"suit":1},{"rank":3,"suit":4},{"rank":7,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":8},{"rank":12,"suit":4},{"rank":7,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":4},{"rank":4,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":4},{"rank":9,"suit":8},{"rank":5,"suit":4},{"rank":9,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":1},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":4,"suit":4},{"rank":4,"suit":1},{"rank":7,"suit":16},{"rank":7,"suit":16},{"rank":2,"suit":1},{"rank":14,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":4},{"rank":9,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":13,"suit":16},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":4},{"rank":12,"suit":16},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":1},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":12,"suit":8},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":4,"suit":8},{"rank":9,"suit":1},{"rank":6,"suit":16},{"rank":13,"suit":1},{"rank":14,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":2,"suit":8},{"rank":3,"suit":8},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":3,"suit":1},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":1},{"rank":6,"suit":16},{"rank":11,"suit":1},{"rank":9,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":4}]},{"seed":752801,"deck":[{"rank":7,"suit":1},{"rank":6,"suit":16},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":4,"suit":16},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":7,"suit":8},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":1},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":16},{"rank":10,"suit":4},{"rank":5,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":2,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":16},{"rank":5,"suit":4},{"rank":7,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":1},{"rank":7,"suit":8},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":13,"suit":8},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":12,"suit":1},{"rank":7,"suit":16},{"rank":14,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":1},{"rank":2,"suit":4},{"rank":13,"suit":1},{"rank":6,"suit":4},{"rank":14,"suit":1},{"rank":9,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":4},{"rank":3,"suit":1},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":4},{"rank":4,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":5,"suit":1},{"rank":14,"suit":16},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":4},{"rank":4,"suit":8},{"rank":7,"suit":8},{"rank":11,"suit":8},{"rank":13,"suit":16},{"rank":6,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":12,"suit":4},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":8},{"rank":5,"suit":8},{"rank":10,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":16},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":7,"suit":4},{"rank":3,"suit":16},{"rank":9,"suit":16},{"rank":2,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":12,"suit":1},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":8,"suit":1},{"rank":3,"suit":4},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":9,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":8},{"rank":8,"suit":1},{"rank":10,"suit":16},{"rank":13,"suit":4},{"rank":7,"suit":16},{"rank":10,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":5,"suit":4},{"rank":11,"suit":16},{"rank":4,"suit":1},{"rank":6,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":16},{"rank":14,"suit":4},{"rank":2,"suit":8},{"rank":11,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":8},{"rank":6,"suit":4},{"rank":3,"suit":4},{"rank":5,"suit":16},{"rank":14,"suit":16},{"rank":4,"suit":1},{"rank":3,"suit":8},{"rank":14,"suit":16},{"rank":12,"suit":16},{"rank":4,"suit":8},{"rank":12,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":11,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":4},{"rank":4,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":1},{"rank":13,"suit":1},{"rank":2,"suit":16},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":1},{"rank":7,"suit":4},{"rank":6,"suit":1},{"rank":10,"suit":4},{"rank":6,"suit":1},{"rank":6,"suit":1},{"rank":10,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":4},{"rank":8,"suit":16},{"rank":11,"suit":1},{"rank":13,"suit":4},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":14,"suit":16},{"rank":5,"suit":8},{"rank":12,"suit":4},{"rank":2,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":16},{"rank":12,"suit":1},{"rank":8,"suit":8},{"rank":3,"suit":4},{"rank":8,"suit":4},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":16},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":11,"suit":8},{"rank":10,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":16},{"rank":12,"suit":16},{"rank":10,"suit":1},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":3,"suit":8},{"rank":14,"suit":4},{"rank":5,"suit":4},{"rank":2,"suit":4},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":10,"suit":16}]},{"seed":752802,"deck":[{"rank":11,"suit":1},{"rank":2,"suit":8},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":6,"suit":4},{"rank":6,"suit":1},{"rank":4,"suit":16},{"rank":11,"suit":8},{"rank":2,"suit":8},{"rank":8,"suit":4},{"rank":8,"suit":1},{"rank":14,"suit":4},{"rank":7,"suit":8},{"rank":3,"suit":8},{"rank":3,"suit":1},{"rank":4,"suit":16},{"rank":7,"suit":4},{"rank":2,"suit":1},{"rank":2,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":4},{"rank":5,"suit":1},{"rank":5,"suit":4},{"rank":4,"suit":16},{"rank":5,"suit":16},{"rank":11,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":4},{"rank":8,"suit":4},{"rank":10,"suit":8},{"rank":3,"suit":1},{"rank":2,"suit":8},{"rank":12,"suit":16},{"rank":4,"suit":1},{"rank":11,"suit":16},{"rank":3,"suit":1},{"rank":6,"suit":8},{"rank":9,"suit":8},{"rank":8,"suit":1},{"rank":5,"suit":16},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":2,"suit":8},{"rank":13,"suit":8},{"rank":14,"suit":4},{"rank":4,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":3,"suit":8},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":11,"suit":8},{"rank":9,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":8},{"rank":6,"suit":16},{"rank":2,"suit":1},{"rank":5,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":16},{"rank":5,"suit":16},{"rank":9,"suit":8},{"rank":7,"suit":1},{"rank":9,"suit":16},{"rank":7,"suit":8},{"rank":4,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":8},{"rank":12,"suit":8},{"rank":7,"suit":8},{"rank":14,"suit":16},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":14,"suit":1},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":9,"suit":16},{"rank":5,"suit":8},{"rank":7,"suit":4},{"rank":7,"suit":4},{"rank":5,"suit":4},{"rank":9,"suit":8},{"rank":12,"suit":1},{"rank":8,"suit":16},{"rank":9,"suit":4},{"rank":10,"suit":16},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":2,"suit":16},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":12,"suit":8},{"rank":4,"suit":1},{"rank":10,"suit":16},{"rank":11,"suit":4},{"rank":12,"suit":1},{"rank":7,"suit":1},{"rank":6,"suit":1},{"rank":9,"suit":4},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":8,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":3,"suit":1},{"rank":5,"suit":1},{"rank":8,"suit":4},{"rank":13,"suit":1},{"rank":12,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":4},{"rank":14,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":16},{"rank":12,"suit":1},{"rank":13,"suit":1},{"rank":8,"suit":16},{"rank":12,"suit":16},{"rank":12,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":8},{"rank":3,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":16},{"rank":2,"suit":16},{"rank":13,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":1},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":11,"suit":1},{"rank":10,"suit":4},{"rank":9,"suit":8},{"rank":7,"suit":4},{"rank":12,"suit":4},{"rank":5,"suit":16},{"rank":5,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":4},{"rank":2,"suit":1},{"rank":8,"suit":8},{"rank":5,"suit":4},{"rank":13,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":1},{"rank":9,"suit":4},{"rank":12,"suit":16},{"rank":7,"suit":16},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":11,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":3,"suit":8},{"rank":7,"suit":16},{"rank":13,"suit":8},{"rank":11,"suit":1},{"rank":7,"suit":1},{"rank":2,"suit":4},{"rank":8,"suit":1},{"rank":13,"suit":16},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":8,"suit":4},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":1},{"rank":3,"suit":4},{"rank":12,"suit":4},{"rank":6,"suit":16},{"rank":6,"suit":1},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":8,"suit":16},{"rank":10,"suit":16},{"rank":8,"suit":1},{"rank":14,"suit":16},{"rank":14,"suit":8},{"rank":4,"suit":8},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":4}]},{"seed":752803,"deck":[{"rank":3,"suit":4},{"rank":12,"suit":8},{"rank":8,"suit":1},{"rank":12,"suit":1},{"rank":11,"suit":1},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":14,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":16},{"rank":10,"suit":1},{"rank":9,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":6,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":8},{"rank":10,"suit":8},{"rank":11,"suit":16},{"rank":3,"suit":16},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":10,"suit":1},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":4,"suit":1},{"rank":4,"suit":1},{"rank":7,"suit":1},{"rank":11,"suit":1},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":4},{"rank":4,"suit":8},{"rank":10,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":10,"suit":1},{"rank":11,"suit":4},{"rank":11,"suit":8},{"rank":7,"suit":4},{"rank":14,"suit":16},{"rank":9,"suit":1},{"rank":14,"suit":16},{"rank":11,"suit":4},{"rank":7,"suit":16},{"rank":7,"suit":8},{"rank":5,"suit":1},{"rank":5,"suit":1},{"rank":4,"suit":4},{"rank":10,"suit":1},{"rank":2,"suit":4},{"rank":3,"suit":4},{"rank":8,"suit":16},{"rank":2,"suit":8},{"rank":12,"suit":4},{"rank":12,"suit":4},{"rank":14,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":13,"suit":8},{"rank":5,"suit":16},{"rank":13,"suit":16},{"rank":4,"suit":4},{"rank":12,"suit":1},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":16},{"rank":10,"suit":8},{"rank":8,"suit":8},{"rank":5,"suit":8},{"rank":4,"suit":8},{"rank":13,"suit":16},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":2,"suit":16},{"rank":4,"suit":1},{"rank":2,"suit":16},{"rank":6,"suit":4},{"rank":5,"suit":4},{"rank":12,"suit":8},{"rank":14,"suit":4},{"rank":13,"suit":8},{"rank":9,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":9,"suit":1},{"rank":12,"suit":16},{"rank":3,"suit":8},{"rank":13,"suit":1},{"rank":6,"suit":1},{"rank":13,"suit":16},{"rank":10,"suit":8},{"rank":14,"suit":4},{"rank":9,"suit":8},{"rank":2,"suit":4},{"rank":13,"suit":4},{"rank":3,"suit":8},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":13,"suit":4},{"rank":5,"suit":16},{"rank":12,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":4},{"rank":11,"suit":16},{"rank":8,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":8,"suit":4},{"rank":5,"suit":4},{"rank":11,"suit":8},{"rank":6,"suit":8},{"rank":11,"suit":16},{"rank":13,"suit":4},{"rank":4,"suit":16},{"rank":3,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":10,"suit":8},{"rank":2,"suit":4},{"rank":3,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":1},{"rank":6,"suit":4},{"rank":13,"suit":1},{"rank":2,"suit":1},{"rank":3,"suit":1},{"rank":12,"suit":1},{"rank":14,"suit":1},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":2,"suit":1},{"rank":7,"suit":4},{"rank":5,"suit":1},{"rank":10,"suit":16},{"rank":8,"suit":16},{"rank":11,"suit":4},{"rank":6,"suit":8},{"rank":7,"suit":16},{"rank":6,"suit":8},{"rank":2,"suit":8},{"rank":4,"suit":16},{"rank":2,"suit":4},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":11,"suit":4},{"rank":3,"suit":4},{"rank":14,"suit":1},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":16},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":8},{"rank":3,"suit":1},{"rank":11,"suit":8},{"rank":8,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":4},{"rank":4,"suit":16},{"rank":7,"suit":8},{"rank":8,"suit":8},{"rank":11,"suit":8},{"rank":10,"suit":4},{"rank":8,"suit":1},{"rank":2,"suit":1},{"rank":14,"suit":8},{"rank":6,"suit":1},{"rank":2,"suit":16},{"rank":7,"suit":8},{"rank":10,"suit":4},{"rank":6,"suit":8},{"rank":14,"suit":16},{"rank":9,"suit":4},{"rank":5,"suit":8},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":7,"suit":16},{"rank":2,"suit":8},{"rank":9,"suit":1},{"rank":13,"suit":16},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":16},{"rank":9,"suit":4},{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":5,"suit":16},{"rank":8,"suit":16},{"rank":6,"suit":1},{"rank":13,"suit":1},{"rank":11,"suit":1},{"rank":5,"suit":8},{"rank":5,"suit":1},{"rank":6,"suit":16},{"rank":9,"suit":16}]},{"seed":752804,"deck":[{"rank":8,"suit":4},{"rank":7,"suit":1},{"rank":9,"suit":8},{"rank":4,"suit":1},{"rank":12,"suit":8},{"rank":7,"suit":4},{"rank":9,"suit":1},{"rank":11,"suit":8},{"rank":12,"suit":16},{"rank":2,"suit":1},{"rank":11,"suit":8},{"rank":5,"suit":8},{"rank":2,"suit":4},{"rank":11,"suit":8},{"rank":2,"suit":16},{"rank":13,"suit":4},{"rank":12,"suit":4},{"rank":9,"suit":8},{"rank":10,"suit":1},{"rank":10,"suit":8},{"rank":11,"suit":4},{"rank":13,"suit":4},{"rank":12,"suit":16},{"rank":13,"suit":4},{"rank":2,"suit":4},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":9,"suit":16},{"rank":4,"suit":4},{"rank":5,"suit":16},{"rank":7,"suit":8},{"rank":9,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":4},{"rank":3,"suit":1},{"rank":5,"suit":4},{"rank":2,"suit":1},{"rank":6,"suit":1},{"rank":14,"suit":1},{"rank":2,"suit":1},{"rank":5,"suit":1},{"rank":2,"suit":8},{"rank":13,"suit":1},{"rank":11,"suit":16},{"rank":10,"suit":16},{"rank":3,"suit":8},{"rank":8,"suit":8},{"rank":9,"suit":4},{"rank":2,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":2,"suit":8},{"rank":10,"suit":16},{"rank":9,"suit":1},{"rank":8,"suit":8},{"rank":11,"suit":1},{"rank":11,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":16},{"rank":3,"suit":4},{"rank":13,"suit":8},{"rank":6,"suit":4},{"rank":14,"suit":16},{"rank":14,"suit":4},{"rank":4,"suit":1},{"rank":5,"suit":1},{"rank":6,"suit":4},{"rank":2,"suit":4},{"rank":2,"suit":8},{"rank":3,"suit":4},{"rank":11,"suit":4},{"rank":13,"suit":8},{"rank":12,"suit":16},{"rank":7,"suit":1},{"rank":8,"suit":16},{"rank":8,"suit":16},{"rank":8,"suit":4},{"rank":6,"suit":4},{"rank":8,"suit":8},{"rank":7,"suit":1},{"rank":13,"suit":1},{"rank":7,"suit":8},{"rank":13,"suit":1},{"rank":10,"suit":4},{"rank":14,"suit":8},{"rank":3,"suit":8},{"rank":4,"suit":16},{"rank":9,"suit":16},{"rank":4,"suit":8},{"rank":10,"suit":4},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":8,"suit":4},{"rank":5,"suit":16},{"rank":4,"suit":16},{"rank":6,"suit":1},{"rank":11,"suit":16},{"rank":6,"suit":8},{"rank":3,"suit":4},{"rank":2,"suit":8},{"rank":6,"suit":16},{"rank":5,"suit":16},{"rank":10,"suit":8},{"rank":7,"suit":4},{"rank":10,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":1},{"rank":14,"suit":4},{"rank":12,"suit":8},{"rank":10,"suit":1},{"rank":12,"suit":1},{"rank":5,"suit":4},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":4,"suit":8},{"rank":3,"suit":16},{"rank":12,"suit":4},{"rank":9,"suit":4},{"rank":13,"suit":16},{"rank":11,"suit":1},{"rank":7,"suit":16},{"rank":3,"suit":16},{"rank":6,"suit":8},{"rank":6,"suit":8},{"rank":10,"suit":1},{"rank":5,"suit":8},{"rank":12,"suit":1},{"rank":5,"suit":1},{"rank":7,"suit":16},{"rank":13,"suit":16},{"rank":12,"suit":1},{"rank":7,"suit":8},{"rank":8,"suit":1},{"rank":7,"suit":8},{"rank":11,"suit":16},{"rank":4,"suit":8},{"rank":6,"suit":8},{"rank":5,"suit":4},{"rank":2,"suit":16},{"rank":12,"suit":8},{"rank":3,"suit":16},{"rank":6,"suit":16},{"rank":10,"suit":4},{"rank":8,"suit":8},{"rank":10,"suit":8},{"rank":14,"suit":8},{"rank":6,"suit":16},{"rank":8,"suit":1},{"rank":12,"suit":4},{"rank":8,"suit":1},{"rank":10,"suit":1},{"rank":13,"suit":8},{"rank":8,"suit":1},{"rank":3,"suit":1},{"rank":13,"suit":1},{"rank":13,"suit":4},{"rank":6,"suit":1},{"rank":12,"suit":8},{"rank":5,"suit":8},{"rank":13,"suit":8},{"rank":6,"suit":16},{"rank":3,"suit":4},{"rank":5,"suit":1},{"rank":12,"suit":16},{"rank":5,"suit":16},{"rank":14,"suit":1},{"rank":4,"suit":8},{"rank":2,"suit":16},{"rank":10,"suit":16},{"rank":2,"suit":1},{"rank":9,"suit":16},{"rank":9,"suit":4},{"rank":3,"suit":1},{"rank":7,"suit":16},{"rank":11,"suit":4},{"rank":14,"suit":1},{"rank":14,"suit":16},{"rank":6,"suit":4},{"rank":11,"suit":1},{"rank":8,"suit":4},{"rank":9,"suit":16},{"rank":12,"suit":4},{"rank":14,"suit":8},{"rank":9,"suit":8},{"rank":4,"suit":16},{"rank":5,"suit":4},{"rank":4,"suit":1},{"rank":11,"suit":8},{"rank":2,"suit":4},{"rank":7,"suit":16},{"rank":4,"suit":4},{"rank":3,"suit":8},{"rank":11,"suit":1},{"rank":8,"suit":16},{"rank":7,"suit":1},{"rank":3,"suit":16},{"rank":14,"suit":16},{"rank":14,"suit":16},{"rank":9,"suit":8},{"rank":14,"suit":4},{"rank":8,"suit":16},{"rank":7,"suit":4},{"rank":14,"suit":8},{"rank":4,"suit":4},{"rank":5,"suit":8},{"rank":9,"suit":1}]}]' #@param {type:"string"}
hand_limit = 0 #@param {type:"integer"}
allow_short_shoe = True #@param {type:"boolean"}
target_ranks = '2, 4, 6, 9' #@param {type:"string"}


from stats import shoe_stats
from game import payout_table

target_payout = payout_table.PayoutTable.default()
ranks = [int(r) for r in target_ranks.split(',')]

scores = shoe_stats.analyze_json_list_str(
    json_input, agents=None, payout=target_payout,
    hand_limit=hand_limit, allow_short_shoe=allow_short_shoe,
    ranks=ranks)

scores_json = shoe_stats.scores_to_json_str(scores)
print(scores_json)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:43<00:00,  1.63s/it]

[{"752705": [200, 225, 265, 295]}, {"752706": [170, 175, 245, 275]}, {"752707": [175, 265, 300, 325]}, {"752708": [110, 140, 180, 260]}, {"752709": [210, 220, 255, 300]}, {"752710": [180, 200, 280, 305]}, {"752711": [200, 255, 280, 290]}, {"752712": [155, 285, 320, 340]}, {"752713": [195, 255, 310, 400]}, {"752714": [260, 320, 330, 375]}, {"752715": [220, 310, 330, 350]}, {"752716": [330, 345, 360, 375]}, {"752717": [255, 270, 335, 360]}, {"752718": [185, 260, 285, 370]}, {"752719": [330, 355, 405, 475]}, {"752720": [145, 250, 305, 345]}, {"752721": [175, 235, 290, 350]}, {"752722": [245, 275, 310, 315]}, {"752723": [215, 275, 320, 355]}, {"752724": [195, 265, 295, 355]}, {"752725": [200, 225, 295, 310]}, {"752726": [205, 245, 290, 350]}, {"752727": [265, 295, 335, 340]}, {"752728": [275, 335, 340, 400]}, {"752729": [140, 180, 225, 280]}, {"752730": [165, 240, 315, 360]}, {"752731": [150, 205, 230, 260]}, {"752732": [190, 215, 225, 320]}, {"752733": [175, 185, 235, 280]}, {"752734": [185, 200, 220, 245]}, {"752735": [190, 205, 330, 375]}, {"752736": [140, 170, 215, 260]}, {"752737": [265, 320, 365, 385]}, {"752738": [170, 200, 265, 305]}, {"752739": [150, 260, 305, 370]}, {"752740": [270, 310, 340, 475]}, {"752741": [180, 215, 260, 285]}, {"752742": [145, 180, 200, 285]}, {"752743": [170, 210, 255, 385]}, {"752744": [170, 195, 290, 325]}, {"752745": [215, 255, 305, 340]}, {"752746": [195, 285, 330, 390]}, {"752747": [155, 175, 210, 250]}, {"752748": [390, 545, 550, 580]}, {"752749": [285, 300, 390, 415]}, {"752750": [305, 345, 355, 430]}, {"752751": [280, 300, 310, 410]}, {"752752": [245, 250, 305, 340]}, {"752753": [205, 220, 270, 345]}, {"752754": [325, 365, 395, 475]}, {"752755": [195, 220, 280, 320]}, {"752756": [165, 230, 235, 355]}, {"752757": [230, 285, 325, 385]}, {"752758": [95, 130, 175, 245]}, {"752759": [245, 275, 305, 375]}, {"752760": [195, 255, 285, 345]}, {"752761": [165, 210, 245, 255]}, {"752762": [250, 300, 310, 350]}, {"752763": [190, 220, 240, 270]}, {"752764": [295, 335, 345, 390]}, {"752765": [250, 290, 335, 370]}, {"752766": [195, 230, 280, 340]}, {"752767": [320, 350, 390, 450]}, {"752768": [180, 185, 205, 300]}, {"752769": [225, 245, 355, 410]}, {"752770": [250, 285, 350, 410]}, {"752771": [165, 250, 320, 355]}, {"752772": [135, 200, 215, 295]}, {"752773": [135, 280, 305, 355]}, {"752774": [230, 270, 290, 315]}, {"752775": [310, 345, 400, 410]}, {"752776": [175, 195, 230, 270]}, {"752777": [235, 295, 370, 415]}, {"752778": [150, 230, 245, 270]}, {"752779": [205, 270, 295, 325]}, {"752780": [140, 165, 200, 230]}, {"752781": [350, 395, 485, 530]}, {"752782": [215, 245, 360, 380]}, {"752783": [150, 200, 230, 280]}, {"752784": [200, 260, 350, 440]}, {"752785": [170, 200, 220, 245]}, {"752786": [195, 240, 285, 440]}, {"752787": [210, 310, 365, 440]}, {"752788": [335, 380, 430, 490]}, {"752789": [245, 355, 400, 495]}, {"752790": [110, 185, 200, 265]}, {"752791": [190, 305, 325, 370]}, {"752792": [200, 220, 240, 315]}, {"752793": [245, 300, 360, 420]}, {"752794": [270, 345, 395, 1215]}, {"752795": [315, 335, 400, 495]}, {"752796": [165, 200, 230, 255]}, {"752797": [175, 180, 195, 270]}, {"752798": [255, 285, 295, 360]}, {"752799": [380, 435, 475, 620]}, {"752800": [340, 385, 390, 480]}, {"752801": [180, 215, 290, 310]}, {"752802": [115, 235, 300, 320]}, {"752803": [205, 230, 260, 285]}, {"752804": [245, 310, 320, 365]}]

In [14]:
# [list(s) for s in compute_targets(np.array(scores)).tolist()]
import numpy as np
type(np.array([s[1] for s in scores]).tolist()[0][0])

int

In [17]:
import numpy as np
score_a = np.array([s[1] for s in scores])
targets = shoe_stats.compute_targets(score_a)
[list(target_scores) for target_scores in targets]

[[200, 255, 265, 295],
 [170, 195, 245, 275],
 [175, 255, 270, 325],
 [105, 135, 180, 260],
 [155, 200, 220, 255],
 [180, 200, 220, 300],
 [210, 260, 290, 310],
 [155, 295, 320, 350],
 [170, 215, 260, 315],
 [260, 280, 320, 365],
 [220, 310, 340, 420],
 [305, 330, 360, 425],
 [205, 255, 295, 355],
 [170, 285, 370, 405],
 [310, 330, 360, 415],
 [145, 230, 255, 305],
 [220, 265, 290, 350],
 [245, 305, 315, 335],
 [240, 275, 345, 355],
 [165, 275, 350, 355],
 [225, 265, 280, 395],
 [230, 255, 315, 350],
 [250, 290, 330, 340],
 [290, 320, 335, 365],
 [170, 185, 245, 285],
 [240, 315, 360, 370],
 [170, 205, 230, 285],
 [190, 215, 230, 320],
 [195, 235, 275, 285],
 [185, 200, 220, 305],
 [190, 260, 300, 375],
 [140, 170, 215, 280],
 [270, 315, 365, 440],
 [180, 230, 285, 305],
 [150, 260, 295, 365],
 [270, 335, 435, 475],
 [175, 195, 260, 285],
 [100, 130, 180, 285],
 [190, 210, 255, 290],
 [170, 260, 295, 305],
 [220, 275, 325, 345],
 [195, 285, 325, 370],
 [155, 175, 210, 265],
 [390, 500, 550, 590],
 [285, 310, 345, 405],
 [305, 355, 380, 420],
 [280, 300, 345, 365],
 [170, 245, 280, 325],
 [185, 220, 280, 315],
 [325, 365, 395, 550],
 [195, 250, 280, 300],
 [165, 235, 240, 355],
 [225, 295, 340, 375],
 [70, 170, 175, 245],
 [245, 285, 330, 375],
 [200, 265, 285, 345],
 [160, 170, 255, 295],
 [215, 245, 300, 350],
 [200, 220, 240, 290],
 [300, 320, 340, 365],
 [250, 270, 335, 345],
 [175, 210, 285, 365],
 [325, 350, 405, 545],
 [185, 205, 255, 305],
 [210, 245, 295, 355],
 [195, 285, 350, 410],
 [220, 275, 320, 385],
 [135, 170, 255, 295],
 [135, 225, 285, 355],
 [230, 255, 290, 320],
 [310, 345, 370, 410],
 [185, 195, 230, 300],
 [280, 295, 375, 455],
 [165, 240, 255, 270],
 [265, 295, 320, 365],
 [140, 170, 220, 230],
 [350, 370, 405, 530],
 [220, 310, 360, 375],
 [150, 170, 230, 280],
 [200, 260, 350, 425],
 [155, 170, 220, 245],
 [205, 230, 255, 300],
 [210, 275, 320, 440],
 [335, 380, 420, 425],
 [245, 355, 370, 480],
 [155, 185, 225, 265],
 [190, 295, 365, 370],
 [215, 230, 255, 345],
 [245, 360, 365, 455],
 [270, 345, 440, 1205],
 [315, 330, 420, 435],
 [195, 220, 240, 270],
 [180, 195, 240, 270],
 [255, 285, 295, 355],
 [360, 380, 600, 625],
 [345, 385, 480, 525],
 [180, 255, 290, 325],
 [120, 215, 290, 320],
 [170, 225, 255, 305],
 [245, 295, 325, 330]]

In [ ]:
import numpy as np

from agent import player_agent
from game import shoe
from game import poker_game
from game import payout_table

NUM_DECKS = 3


def play_game(num_decks: int = 4):
    np.set_printoptions(precision=1, suppress=True)
    advantage = None
    try:
        advantage = player_agent.advantage_table(num_decks=num_decks)
    except FileNotFoundError:
        print(f'Cannot find advantage table for {num_decks} decks, playing ',
              'without advantage')
    agent = player_agent.CardCountingAgent(advantage=advantage, verbose=True)
    draw_shoe = shoe.InteractiveShoe(num_decks=num_decks)
    payout = payout_table.PayoutTable.default()
    game = poker_game.PokerGame(num_decks=num_decks, draw_shoe=draw_shoe,
                                payout=payout, allow_short_shoe=True)
    agent.play(game, verbose=True)

play_game(num_decks=NUM_DECKS)